version: "3"
networks:
    1panel-network:
        external: true
services:
  clash:
    image: dreamacro/clash-premium
    container_name: clash-premium
    volumes:
      - ./config:/root/.config/clash
      - ./ui:/root/ui
    ports:
      - ${CLASH_PROXY_PORT}:7890
      - ${PANEL_APP_PORT_HTTP}:9090
    restart: unless-stopped
    networks:
        - 1panel-network